import type { FormTemplate } from "./index";

export const eventFeedbackTemplate: FormTemplate = {
  id: "event-feedback",
  name: "Feedback de Evento",
  description: "Avaliação geral, palestrantes, organização, local e sugestões para eventos",
  icon: "CalendarCheck",
  category: "feedback",
  schema: {
    version: 1,
    title: "Avaliação do Evento",
    description: "Ajude-nos a melhorar! Sua avaliação é anônima e leva menos de 3 minutos.",
    settings: {
      allowMultipleSubmissions: false,
      showProgressBar: true,
      shufflePages: false,
      requireAuth: false,
      thankYouTitle: "Obrigado pela avaliação!",
      thankYouMessage: "Seu feedback é essencial para melhorarmos os próximos eventos.",
    },
    theme: {
      primaryColor: "#C4A882",
      backgroundColor: "#0A0A0A",
      fontFamily: "Inter, system-ui, sans-serif",
      borderRadius: 8,
    },
    pages: [
      {
        id: "geral",
        title: "Avaliação geral",
        elements: [
          {
            id: "evt_rating",
            type: "rating",
            label: "Avaliação geral do evento",
            description: "De 1 a 5 estrelas, como você avalia o evento?",
            required: true,
            validation: [],
            conditions: [],
            properties: { max: 5 },
          },
          {
            id: "evt_nps",
            type: "nps",
            label: "Qual a probabilidade de recomendar este evento a um colega?",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 0, max: 10 },
          },
        ],
        conditions: [],
      },
      {
        id: "detalhes",
        title: "Avaliação detalhada",
        elements: [
          {
            id: "evt_palestrantes",
            type: "scale",
            label: "Qualidade dos palestrantes",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "evt_organizacao",
            type: "scale",
            label: "Organização do evento",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "evt_local",
            type: "scale",
            label: "Local / infraestrutura",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "evt_conteudo",
            type: "scale",
            label: "Relevância do conteúdo",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
        ],
        conditions: [],
      },
      {
        id: "sugestoes",
        title: "Sugestões",
        elements: [
          {
            id: "evt_melhor",
            type: "textarea",
            label: "O que mais gostou no evento?",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
          },
          {
            id: "evt_melhorar",
            type: "textarea",
            label: "O que podemos melhorar?",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
          },
          {
            id: "evt_temas",
            type: "textarea",
            label: "Que temas gostaria de ver nos próximos eventos?",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
          },
        ],
        conditions: [],
      },
    ],
  },
};
