import type { FormTemplate } from "./index";

export const leadCaptureTemplate: FormTemplate = {
  id: "lead-capture",
  name: "Captação de Leads",
  description: "Formulário de contato e qualificação com nome, email, empresa, cargo e interesse",
  icon: "UserPlus",
  category: "lead_gen",
  schema: {
    version: 1,
    title: "Fale conosco",
    description: "Preencha seus dados e entraremos em contato em breve.",
    settings: {
      allowMultipleSubmissions: false,
      showProgressBar: false,
      shufflePages: false,
      requireAuth: false,
      thankYouTitle: "Recebemos seu contato!",
      thankYouMessage: "Nossa equipe entrará em contato em até 24 horas úteis.",
    },
    theme: {
      primaryColor: "#C4A882",
      backgroundColor: "#0A0A0A",
      fontFamily: "Inter, system-ui, sans-serif",
      borderRadius: 8,
    },
    pages: [
      {
        id: "contact",
        title: "Seus dados",
        elements: [
          {
            id: "lead_name",
            type: "text",
            label: "Nome completo",
            required: true,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "Seu nome",
          },
          {
            id: "lead_email",
            type: "email",
            label: "Email",
            required: true,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "seu@email.com",
          },
          {
            id: "lead_phone",
            type: "phone",
            label: "Telefone / WhatsApp",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "(11) 99999-9999",
          },
          {
            id: "lead_company",
            type: "text",
            label: "Empresa",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "Nome da empresa",
          },
          {
            id: "lead_role",
            type: "text",
            label: "Cargo",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "Ex: Gerente de Marketing",
          },
          {
            id: "lead_interest",
            type: "radio",
            label: "Qual seu principal interesse?",
            required: true,
            validation: [],
            conditions: [],
            properties: {
              options: [
                { label: "Conhecer o produto/serviço", value: "conhecer" },
                { label: "Solicitar orçamento", value: "orcamento" },
                { label: "Suporte técnico", value: "suporte" },
                { label: "Parceria", value: "parceria" },
                { label: "Outro", value: "outro" },
              ],
            },
          },
          {
            id: "lead_budget",
            type: "select",
            label: "Faixa de investimento",
            required: false,
            validation: [],
            conditions: [],
            properties: {
              options: [
                { label: "Até R$ 1.000", value: "ate_1k" },
                { label: "R$ 1.000 - R$ 5.000", value: "1k-5k" },
                { label: "R$ 5.000 - R$ 20.000", value: "5k-20k" },
                { label: "R$ 20.000 - R$ 50.000", value: "20k-50k" },
                { label: "Acima de R$ 50.000", value: "acima_50k" },
                { label: "Prefiro não informar", value: "nao_informar" },
              ],
            },
          },
        ],
        conditions: [],
      },
    ],
  },
};
