import type { FormTemplate } from "./index";

export const organizationalClimateTemplate: FormTemplate = {
  id: "organizational-climate",
  name: "Pesquisa de Clima Organizacional",
  description: "Escalas de satisfação, NPS empregador, feedback anônimo sobre ambiente de trabalho",
  icon: "Building2",
  category: "survey",
  schema: {
    version: 1,
    title: "Pesquisa de Clima Organizacional",
    description: "Esta pesquisa é anônima e confidencial. Sua sinceridade nos ajuda a construir um ambiente melhor.",
    settings: {
      allowMultipleSubmissions: false,
      showProgressBar: true,
      shufflePages: false,
      requireAuth: false,
      thankYouTitle: "Obrigado pela sua participação!",
      thankYouMessage: "Suas respostas são confidenciais e serão analisadas de forma agregada para melhorias.",
    },
    theme: {
      primaryColor: "#C4A882",
      backgroundColor: "#0A0A0A",
      fontFamily: "Inter, system-ui, sans-serif",
      borderRadius: 8,
    },
    pages: [
      {
        id: "satisfacao",
        title: "Satisfação geral",
        elements: [
          {
            id: "clima_nps",
            type: "nps",
            label: "De 0 a 10, qual a probabilidade de recomendar esta empresa como local de trabalho?",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 0, max: 10 },
          },
          {
            id: "clima_satisfacao",
            type: "scale",
            label: "Satisfação geral com o trabalho",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Muito insatisfeito", maxLabel: "Muito satisfeito" },
          },
          {
            id: "clima_permanencia",
            type: "radio",
            label: "Pretende continuar na empresa nos próximos 12 meses?",
            required: true,
            validation: [],
            conditions: [],
            properties: {
              options: [
                { label: "Sim, com certeza", value: "sim_certeza" },
                { label: "Provavelmente sim", value: "provavelmente_sim" },
                { label: "Estou em dúvida", value: "duvida" },
                { label: "Provavelmente não", value: "provavelmente_nao" },
                { label: "Não", value: "nao" },
              ],
            },
          },
        ],
        conditions: [],
      },
      {
        id: "dimensoes",
        title: "Dimensões do clima",
        elements: [
          {
            id: "clima_lideranca",
            type: "scale",
            label: "Qualidade da liderança direta",
            description: "Como avalia seu gestor imediato?",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "clima_comunicacao",
            type: "scale",
            label: "Comunicação interna",
            description: "Clareza e transparência das informações da empresa",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "clima_crescimento",
            type: "scale",
            label: "Oportunidades de crescimento",
            description: "Desenvolvimento profissional e plano de carreira",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "clima_remuneracao",
            type: "scale",
            label: "Remuneração e benefícios",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
          {
            id: "clima_equilibrio",
            type: "scale",
            label: "Equilíbrio vida pessoal e profissional",
            required: true,
            validation: [],
            conditions: [],
            properties: { min: 1, max: 5, minLabel: "Ruim", maxLabel: "Excelente" },
          },
        ],
        conditions: [],
      },
      {
        id: "aberto",
        title: "Comentários",
        elements: [
          {
            id: "clima_positivo",
            type: "textarea",
            label: "O que há de melhor em trabalhar aqui?",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
          },
          {
            id: "clima_melhorar",
            type: "textarea",
            label: "O que mais precisa melhorar?",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
          },
        ],
        conditions: [],
      },
    ],
  },
};
