import type { FormTemplate } from "./index";

export const registrationTemplate: FormTemplate = {
  id: "registration",
  name: "Cadastro / Inscrição",
  description: "Dados pessoais, contato, preferências e aceite de termos",
  icon: "ClipboardList",
  category: "registration",
  schema: {
    version: 1,
    title: "Formulário de Inscrição",
    description: "Preencha seus dados para completar a inscrição.",
    settings: {
      allowMultipleSubmissions: false,
      showProgressBar: true,
      shufflePages: false,
      requireAuth: false,
      thankYouTitle: "Inscrição realizada!",
      thankYouMessage: "Sua inscrição foi confirmada. Você receberá um email com mais informações.",
    },
    theme: {
      primaryColor: "#C4A882",
      backgroundColor: "#0A0A0A",
      fontFamily: "Inter, system-ui, sans-serif",
      borderRadius: 8,
    },
    pages: [
      {
        id: "dados",
        title: "Dados pessoais",
        elements: [
          {
            id: "reg_name",
            type: "text",
            label: "Nome completo",
            required: true,
            validation: [],
            conditions: [],
            properties: {},
          },
          {
            id: "reg_email",
            type: "email",
            label: "Email",
            required: true,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "seu@email.com",
          },
          {
            id: "reg_phone",
            type: "phone",
            label: "Telefone / WhatsApp",
            required: true,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "(11) 99999-9999",
          },
          {
            id: "reg_birth",
            type: "date",
            label: "Data de nascimento",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
          },
          {
            id: "reg_city",
            type: "text",
            label: "Cidade / Estado",
            required: false,
            validation: [],
            conditions: [],
            properties: {},
            placeholder: "Ex: São Paulo - SP",
          },
        ],
        conditions: [],
      },
      {
        id: "preferencias",
        title: "Preferências",
        elements: [
          {
            id: "reg_how",
            type: "select",
            label: "Como nos conheceu?",
            required: true,
            validation: [],
            conditions: [],
            properties: {
              options: [
                { label: "Redes sociais", value: "redes_sociais" },
                { label: "Indicação de amigo", value: "indicacao" },
                { label: "Google / busca", value: "google" },
                { label: "Email / newsletter", value: "email" },
                { label: "Evento", value: "evento" },
                { label: "Outro", value: "outro" },
              ],
            },
          },
          {
            id: "reg_interests",
            type: "multiselect",
            label: "Áreas de interesse",
            required: false,
            validation: [],
            conditions: [],
            properties: {
              options: [
                { label: "Tecnologia", value: "tecnologia" },
                { label: "Negócios", value: "negocios" },
                { label: "Marketing", value: "marketing" },
                { label: "Design", value: "design" },
                { label: "Educação", value: "educacao" },
                { label: "Saúde", value: "saude" },
              ],
            },
          },
          {
            id: "reg_terms",
            type: "checkbox",
            label: "Li e aceito os termos de uso e política de privacidade",
            required: true,
            validation: [],
            conditions: [],
            properties: {},
          },
        ],
        conditions: [],
      },
    ],
  },
};
